version: "3.8"

services:
  orthanc-router:
    container_name: router
    command: /root/conf/ --no-jobs
    build:
      context: ./orthanc/router
      dockerfile: ./Dockerfile
      args:
        - DICOM_AET=CCR
        - ORTHANC_ADMIN=$ORTHANC_ADMIN
        - ORTHANC_ADMIN_PASSWORD=$ORTHANC_ADMIN_PASSWORD
    ports:
      - 4242:4242
    depends_on:
      - general-writer
      - xray-writer
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  general-writer:
    container_name: general-writer
    command: /root/conf/
    build:
      context: ./orthanc/writer
      dockerfile: ./Dockerfile
      args:
        - DICOM_AET=GENERAL
        - ORIGIN=general-writer
        - ORTHANC_ADMIN=$ORTHANC_ADMIN
        - ORTHANC_ADMIN_PASSWORD=$ORTHANC_ADMIN_PASSWORD
        - ORTHANC_USER=$ORTHANC_USER
        - ORTHANC_USER_PASSWORD=$ORTHANC_USER_PASSWORD
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  xray-writer:
    container_name: xray-writer
    command: /root/conf/
    build:
      context: ./orthanc/writer
      dockerfile: ./Dockerfile
      args:
        - DICOM_AET=XRAY
        - ORIGIN=xray-writer
        - ORTHANC_ADMIN=$ORTHANC_ADMIN
        - ORTHANC_ADMIN_PASSWORD=$ORTHANC_ADMIN_PASSWORD
        - ORTHANC_USER=$ORTHANC_USER
        - ORTHANC_USER_PASSWORD=$ORTHANC_USER_PASSWORD
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"