version: "3.8"

services:
  orthanc-router:
    container_name: router
    command: /root/conf/ --no-jobs
    build:
      context: ./orthanc/router
      dockerfile: ./Dockerfile
      args:
        - DICOM_AET=CCR
        - ORTHANC_ADMIN=$ORTHANC_ADMIN
        - ORTHANC_ADMIN_PASSWORD=$ORTHANC_ADMIN_PASSWORD
    ports:
      - 4242:4242
    depends_on:
      - simple-general-writer
      - xray-writer
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  simple-general-writer:
    container_name: simple-general-writer
    command: /root/conf/
    build:
      context: ./orthanc/writer
      dockerfile: ./Dockerfile
      args:
        - DICOM_AET=GENERAL
        - ORIGIN=simple-general-writer
        - ORTHANC_ADMIN=$ORTHANC_ADMIN
        - ORTHANC_ADMIN_PASSWORD=$ORTHANC_ADMIN_PASSWORD
        - ORTHANC_USER=$ORTHANC_USER
        - ORTHANC_USER_PASSWORD=$ORTHANC_USER_PASSWORD
    restart: unless-stopped
    depends_on:
      - simple-router-db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  xray-writer:
    container_name: xray-writer
    command: /root/conf/
    build:
      context: ./orthanc/writer
      dockerfile: ./Dockerfile
      args:
        - DICOM_AET=XRAY
        - ORIGIN=xray-writer
        - ORTHANC_ADMIN=$ORTHANC_ADMIN
        - ORTHANC_ADMIN_PASSWORD=$ORTHANC_ADMIN_PASSWORD
        - ORTHANC_USER=$ORTHANC_USER
        - ORTHANC_USER_PASSWORD=$ORTHANC_USER_PASSWORD
    restart: unless-stopped
    depends_on:
      - simple-router-db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  simple-router-db:
    container_name: simple-router-db
    image: mysql:5.7
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password", "--log-bin-trust-function-creators=1"]
    environment:
      MYSQL_DATABASE: 'otc'
      MYSQL_USER: 'otc'
      MYSQL_PASSWORD: 'otc'
      MYSQL_ROOT_PASSWORD: 'otc'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - simple-index:/var/lib/mysql:Z
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  simple-storage:
  simple-index: